from typing import List

from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    """Incoming API request."""

    request: str = Field(
        ...,
        min_length=10,
        description="Natural language request from the user."
    )


class PlannerOutput(BaseModel):
    """Execution plan generated by the planner."""

    goal: str

    assumptions: List[str]

    tasks: List[str]


class ExecutionResult(BaseModel):
    """Generated document content."""

    title: str

    content: str


class AgentResponse(BaseModel):
    """Final API response."""

    status: str

    goal: str

    assumptions: List[str]

    plan: List[str]

    document_path: str