"""
Data models used by the Autonomous AI Agent.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from uuid import uuid4

class AgentBaseModel(BaseModel):
    """
    Base model for all AI agent models.

    Provides common validation rules and configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

class Task(AgentBaseModel):
    """
    Represents a single executable task generated by the planner.
    """

    task_id: int = Field(
        ...,
        ge=1,
        description="Sequential task identifier.",
    )

    title: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="Short title describing the task.",
    )

    status: Literal[
        "pending",
        "completed",
        "failed",
    ] = Field(
        default="pending",
        description="Current execution status.",
    )

    output: str | None = Field(
        default=None,
        description="Generated output after task execution.",
    )

    error: str | None = Field(
        default=None,
        description="Error message if task execution fails.",
    )

    execution_time: float | None = Field(
        default=None,
        ge=0,
        description="Execution time in seconds.",
    )

class PlannerOutput(AgentBaseModel):
    """
    Structured execution plan generated by the planner.
    """

    goal: str = Field(
        ...,
        min_length=1,
        description="Primary objective derived from the user's request.",
    )

    assumptions: list[str] = Field(
        default_factory=list,
        description=(
            "Reasonable assumptions made by the planner "
            "when information is incomplete."
        ),
    )

    tasks: list[Task] = Field(
        default_factory=list,
        min_length=1,
        description="Ordered list of executable tasks.",
    )

class ExecutionResult(AgentBaseModel):
    """
    Represents the outcome of executing the execution plan.
    """

    goal: str = Field(
        ...,
        description="Original execution goal.",
    )

    assumptions: list[str] = Field(
        default_factory=list,
        description="Planner assumptions.",
    )

    tasks: list[Task] = Field(
        default_factory=list,
        description="Tasks after execution.",
    )

    combined_output: str = Field(
        default="",
        description="Merged output from all completed tasks.",
    )

    regenerated_output: str | None = Field(
        default=None,
        description=(
            "Improved document generated after "
            "reflection and regeneration."
        ),
    )

    completed_tasks: int = Field(
        default=0,
        ge=0,
        description="Number of successfully completed tasks.",
    )

    failed_tasks: int = Field(
        default=0,
        ge=0,
        description="Number of failed tasks.",
    )

    execution_summary: str | None = Field(
        default=None,
        description="Summary of execution.",
    )

class WorkflowContext(AgentBaseModel):
    """
    Shared context propagated through the
    complete execution workflow.
    """

    request_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique workflow identifier.",
    )

class ReflectionIssue(AgentBaseModel):
    """
    Represents a single issue identified during reflection.
    """

    title: str = Field(
        ...,
        min_length=3,
        max_length=150,
        description="Short title describing the issue.",
    )

    description: str = Field(
        ...,
        min_length=5,
        description="Detailed explanation of the issue.",
    )

    evidence: str = Field(
        ...,
        min_length=5,
        description=(
            "Evidence supporting why the issue "
            "was identified."
        ),
    )

    severity: Literal[
        "low",
        "medium",
        "high",
    ] = Field(
        ...,
        description="Severity level of the issue.",
    )

class ReflectionSuggestion(AgentBaseModel):
    """
    Represents a recommendation generated during reflection.
    """

    title: str = Field(
        ...,
        min_length=3,
        max_length=150,
        description="Short title of the recommendation.",
    )

    description: str = Field(
        ...,
        min_length=5,
        description=(
            "Detailed recommendation for improving "
            "the execution."
        ),
    )

class ReflectionResult(AgentBaseModel):
    """
    Represents the structured output generated by
    the Reflection Engine.
    """

    overall_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Overall quality score.",
    )

    confidence: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Confidence level of the reflection "
            "assessment."
        ),
    )

    needs_revision: bool = Field(
        ...,
        description=(
            "Indicates whether the execution "
            "requires revision."
        ),
    )

    strengths: list[str] = Field(
        default_factory=list,
        description=(
            "Positive aspects identified during "
            "reflection."
        ),
    )

    issues: list[ReflectionIssue] = Field(
        default_factory=list,
        description="Issues found during reflection.",
    )

    suggestions: list[ReflectionSuggestion] = Field(
        default_factory=list,
        description=(
            "Recommendations for improving "
            "the execution."
        ),
    )

    summary: str = Field(
        ...,
        min_length=10,
        description="Overall reflection summary.",
    )

class ReflectionContext(AgentBaseModel):
    """
    Reflection information included in the generated document.
    """

    overall_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Overall quality score.",
    )

    confidence: int = Field(
        ...,
        ge=0,
        le=100,
        description="Confidence level of the reflection assessment.",
    )

    needs_revision: bool = Field(
        ...,
        description="Indicates whether the document requires revision.",
    )

    strengths: list[str] = Field(
        default_factory=list,
        description="Positive aspects identified during reflection.",
    )

    issues: list[ReflectionIssue] = Field(
        default_factory=list,
        description="Issues identified during reflection.",
    )

    suggestions: list[ReflectionSuggestion] = Field(
        default_factory=list,
        description="Recommendations for improving the document.",
    )

    summary: str = Field(
        ...,
        min_length=10,
        description="Overall reflection summary.",
    )

# ======================================================================
# Regeneration Models
# ======================================================================

class RegenerationRequest(AgentBaseModel):
    """
    Input provided to the Regenerator.
    """

    execution: ExecutionResult = Field(
        ...,
        description="Original execution result.",
    )

    reflection: ReflectionResult = Field(
        ...,
        description="Reflection feedback.",
    )

class RegenerationResult(AgentBaseModel):
    """
    Result returned by the Regenerator.
    """

    execution: ExecutionResult = Field(
        ...,
        description="Improved execution result.",
    )

    iteration: int = Field(
        default=1,
        ge=1,
        description="Regeneration iteration number.",
    )

    improved: bool = Field(
        default=True,
        description="Whether improvements were applied.",
    )

class DocumentSection(AgentBaseModel):
    """
    Represents a single section in the generated document.
    """

    heading: str = Field(
        ...,
        min_length=1,
        description="Section heading.",
    )

    content: str = Field(
        ...,
        description="Section content.",
    )

class DocumentContext(AgentBaseModel):
    """
    Structured context used by the document generator.
    """

    title: str = Field(
        ...,
        description="Document title.",
    )

    goal: str = Field(
        ...,
        description="Primary goal.",
    )

    assumptions: list[str] = Field(
        default_factory=list,
        description="Planner assumptions.",
    )

    sections: list[DocumentSection] = Field(
        default_factory=list,
        description="Document sections.",
    )

    reflection: ReflectionContext = Field(
        ...,
        description="Reflection report.",
    )

    summary: str = Field(
        default="",
        description="Workflow summary.",
    )


class DocumentResult(AgentBaseModel):
    """
    Metadata returned after generating the document.
    """

    title: str = Field(
        ...,
        description="Document title.",
    )

    filename: str = Field(
        ...,
        description="Generated filename.",
    )

    document_path: str = Field(
        ...,
        description="Location of the generated document.",
    )

    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="Generation timestamp.",
    )

    section_count: int = Field(
        ...,
        ge=0,
        description="Number of generated sections.",
    )

    word_count: int = Field(
        ...,
        ge=0,
        description="Approximate document word count.",
    )