"""
Reflection service responsible for evaluating execution results.
"""

from __future__ import annotations

from agent.llm import LLMService
from agent.models import (
    ExecutionResult,
    ReflectionResult,
    WorkflowContext,
)
from core.exceptions import (
    ConfigurationException,
    LLMException,
    ReflectionException,
    ValidationException,
)
from core.logging_config import get_logger
from core.reflection_prompts import (
    build_reflection_prompt,
)

logger = get_logger(__name__)


class Reflection:
    """
    Reflection service responsible for evaluating
    execution results generated by the Executor.
    """

    def __init__(
        self,
        llm: LLMService,
    ) -> None:
        """
        Initialize the reflection service.

        Args:
            llm:
                LLM service instance.
        """

        self._llm = llm

    async def reflect(
        self,
        workflow: WorkflowContext,
        result: ExecutionResult,
    ) -> ReflectionResult:
        """
        Evaluate an execution result.

        Args:
            workflow:
                Current workflow context.

            result:
                Execution result produced by the Executor.

        Returns:
            ReflectionResult

        Raises:
            ValidationException:
                If the execution result is invalid.

            ConfigurationException:
                If Gemini is not configured.

            LLMException:
                If communication with Gemini fails.

            ReflectionException:
                If an unexpected reflection error occurs.
        """

        if not result.tasks:

            raise ValidationException(
                "Execution result contains no tasks."
            )

        logger.info(
            "[%s] Starting reflection.",
            workflow.request_id,
        )

        try:

            prompt = build_reflection_prompt(
                result,
            )

            reflection = await self._llm.generate_json(
                prompt=prompt,
                output_model=ReflectionResult,
            )

            logger.info(
                "[%s] Reflection completed (Score=%d, Needs Revision=%s).",
                workflow.request_id,
                reflection.overall_score,
                reflection.needs_revision,
            )

            return reflection

        except (
            ConfigurationException,
            ValidationException,
            LLMException,
        ):
            raise

        except Exception as exc:

            logger.exception(
                "Unexpected reflection error."
            )

            raise ReflectionException(
                "Reflection failed unexpectedly."
            ) from exc